backend:
  name: git-gateway
  # name: test-repo
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog_english'
    label: 'Blog English'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'en.md'
    format: 'frontmatter'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - {
          label: 'Header Image',
          name: 'headerImage',
          widget: 'image',
          required: false,
          default: '/img/portfolio-placeholder.jpg',
        }
      - {
          label: 'isFeatured (if ture, the post will add to the featured tab)',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options: ['story', 'work'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  - name: 'blog_chinese'
    label: 'Blog Chinese'
    folder: 'src/pages/blog/cn'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'cn.md'
    format: 'frontmatter'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '摘抄', name: 'excerpt', widget: 'text', required: false }
      - {
          label: '头部图片',
          name: 'headerImage',
          widget: 'image',
          required: false,
          default: '/img/portfolio-placeholder.jpg',
        }
      - {
          label: '是否设为精选',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: '类别',
          name: 'category',
          widget: 'select',
          options: ['故事', '作品'],
        }
      - { label: '正文', name: 'body', widget: 'markdown' }
      - { label: '标签', name: 'tags', widget: 'list' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.en.md'
        label: 'Home Page EN'
        name: 'index-en'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
      - file: 'src/pages/index.cn.md'
        label: 'Home Page CN'
        name: 'index-cn'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
