backend:
  name: git-gateway
  # name: test-repo
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog_english'
    label: 'Blog English'
    folder: 'src/pages/blog/en'
    filter: { field: 'language', value: 'en' }
    create: true
    slug: '{{language}}/{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['en', 'cn'],
          default: 'en',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  - name: 'blog_chinese'
    label: 'Blog Chinese'
    folder: 'src/pages/blog/cn'
    filter: { field: 'language', value: 'cn' }
    create: true
    slug: '{{language}}/{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {
          label: '语言',
          name: 'language',
          widget: 'select',
          options: ['en', 'cn'],
          default: 'cn',
        }
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '描述', name: 'description', widget: 'text' }
      - { label: '正文', name: 'body', widget: 'markdown' }
      - { label: '标签', name: 'tags', widget: 'list' }
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'src/pages/portfolio'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'portfolio-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          default: '/img/portfolio-placeholder.jpg',
        }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
      - file: 'src/pages/portfolio/index.md'
        label: 'Portfolio Page'
        name: 'portfolio'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'portfolio-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
